config/routes.rb
Rails.application.routes.draw do

  resources :switch_initial_configs
  resources :switches


  get 'monitor_glue/status'

  get 'sdn_callback/restore_state'

  match 'net_config_transactions/sort' => 'net_config_transactions#sort', :via=>[:get, :post]
  resources :net_config_transactions, :only => [:index]
  
  get 'owner_group/index'
  get 'group/index'

  get 'admin/index'
  get 'admin'=>'admin#index'
  get 'admin/subnets'
  get 'admin/initialize_sdn_controller'
  get 'admin/playback_to_sdn'
  get 'admin/get_sdn_config'
  get 'admin/ajax_get_groups'
  post 'admin/ajax_set_group'
  get 'admin/ajax_get_members'
  post 'admin/add_subnet'
  get 'admin/links'
  delete 'admin/not_supported'
  
  get 'admin/visualize_switch_setup'
  get 'admin/d3_switch_setup'
  get 'admin/switch_setup'
  
  
  get 'home/logout'=>'home#logout'
  get "no_access" => 'home#no_access'
  get 'home/visualize_sdn'
  get 'home/d3_sdn'
  get 'home/sdn_status'
  
  root 'link_requests#index_get'
  match 'link_requests' => 'link_requests#index_get', :via=>[:get]
  
  post "link_requests/approve"
  post "link_requests/deny"  
  match 'link_requests/sort' => 'link_requests#sort', :via=>[:get, :post]
  resources :link_requests

  get "owner_group/ajax_users"
  post "owner_group/rm_user"
  post 'owner_group/add_user'
  match 'owner_group/sort' => 'owner_group#sort', :via=>[:get, :post]
  resources :owner_group
  

  get "activities/sort"
  resources :activities
  
  resources :links
  
end

app/views/admin/d3_switch_setup.html.erb
<script src="/assets/d3.v3.js"></script>
<style>

path.link {
  fill: none;
  stroke: #666;
  stroke-width: 1.5px;
}

circle {
  fill: #00F;
  stroke: #fff;
  stroke-width: 1.5px;
}

text {
  fill: #000;
  font: 10px sans-serif;
  pointer-events: none;
}

div.nodedetail {
    position: absolute;    
    text-align: left;    
    /* width: 60px;    
    height: 28px;     */   
    padding: 4px;    
    font: 12px sans-serif;    
    background: #EBF0CC;    
    border: 0px;                    
    border-radius: 4px;
}

</style>

<script>

// Define 'div' for nodedetail
var div = d3.select("body")
    .append("div")  // declare the nodedetail div 
    .attr("class", "nodedetail")
    .style("opacity", 0);


// get the data - hardwired during development, but go dynamic for production
//d3.csv("http://localhost:3000/assets/graph-test-network.txt",function(error, links) {

d3.csv("<%=request.base_url%>/admin/switch_setup.csv",function(error, links) {
var nodes = {};

// Compute the distinct nodes from the links.
  links.forEach(function(link) {
    link.source = nodes[link.source] || (nodes[link.source] = {name: link.source});
    link.target = nodes[link.target] || (nodes[link.target] = {name: link.target});
    link.group = link.value;
    
    // accumulate the notes about each link the node is involved in
    if (typeof(link.source.notes) == 'undefined') {
      link.source.notes = link.notes
    } else {
      link.source.notes = link.source.notes + '<br> ' + link.notes
    }
    if (typeof(link.target.notes) == 'undefined') {
      link.target.notes = link.notes
    } else {
      link.target.notes = link.target.notes + '<br> ' + link.notes
    }
  });


var width = 960,
    height = 500;

var force = d3.layout.force()
    .nodes(d3.values(nodes))
    .links(links)
    .size([width, height])
    .linkDistance(125)
    .charge(-500)
    .on("tick", tick)
    .start();

var drag = force.drag()
    .on("dragstart", dragstart);

var color = d3.scale.category10();

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

// build the arrow.
svg.append("svg:defs").selectAll("marker")
    .data(["end"])      // Different link/path types can be defined here
  .enter().append("svg:marker")    // This section adds in the arrows
    .attr("id", String)
    .attr("viewBox", "0 -5 10 10")
    .attr("refX", 15)
    .attr("refY", -1.5)
    .attr("markerWidth", 6)
    .attr("markerHeight", 6)
    .attr("orient", "auto")
    //.style("fill", function(d) { return color(d.value); })
    .style("fill", "#0736A4")
  .append("svg:path")
    .attr("d", "M0,-5L10,0L0,5");

// add the links and the arrows
var path = svg.append("svg:g").selectAll("path")
    .data(force.links())
    .enter().append("svg:path")  
    .attr("class", function(d) { return "link " + d.value; })  
    .style("stroke", function(d) { return color(d.value); })
    .attr("marker-end", "url(#end)");


// define the nodes
var node = svg.selectAll(".node")
    .data(force.nodes())
  .enter().append("g")
    .attr("class", "node")
    .on("click", click)
    .on("dblclick", dblclick)
    .on("mouseover", mouseover)
    .on("mouseout", mouseout)
    .call(drag);

// add the nodes
node.append("circle")
    .style("fill", "#0736A4")
    .attr("r", 5);

// add the text 
node.append("text")
    .attr("x", 12)
    .attr("dy", ".35em")
    .text(function(d) { return d.name; });

// add the curvy lines
function tick() {
    path.attr("d", function(d) {
        var dx = d.target.x - d.source.x,
            dy = d.target.y - d.source.y,
            dr = Math.sqrt(dx * dx + dy * dy);
        return "M" + 
            d.source.x + "," + 
            d.source.y + "A" + 
            dr + "," + dr + " 0 0,1 " + 
            d.target.x + "," + 
            d.target.y;
    });
    node
        .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });
}

// action to take on mouseover
function mouseover(d) {
    d3.select(this).select("text").transition()
    div.transition()
        .duration(500)    
        .style("opacity", 0);
    div.transition()
        .duration(200)    
        .style("opacity", .9);    
    div .html( "<center><b>" + d.name + "</b></center><hr>"+ d.notes + "<br>&nbsp<br>")     
        .style("left", (d3.event.pageX) + "px")             
        .style("top", (d3.event.pageY) + 25 + "px");
}

// action to take on mouseout
function mouseout(d) {		
    div.transition()		
        .duration(500)		
        .style("opacity", 0);	
}

// action to take on mouse click
function click(d) {
    d3.select(this).select("text").transition()
        .duration(750)
        .attr("x", 22)
        .style("fill", "#0736A4")
        .style("stroke", "#0736A4")
        .style("stroke-width", ".5px")
        .style("font", "20px sans-serif");
    d3.select(this).select("circle").transition()
        .duration(750)
        .attr("r", 16)
        .style("fill", "#0736A4");
}

// action to take on mouse double click
function dblclick(d) {
    d3.select(this).select("circle").transition()
        .duration(750)
        .attr("r", 6)
        .style("fill", "#0736A4");
    d3.select(this).select("text").transition()
        .duration(750)
        .attr("x", 12)
        .style("stroke", "none")
        .style("fill", "black")
        .style("stroke", "none")
        .style("font", "10px sans-serif");
    d3.select(this).classed("fixed", d.fixed = false); //subjected the node to force layout again
}

// stop subjecting the node to force layout
function dragstart(d) {
  d3.select(this).classed("fixed", d.fixed = true);
}

//Legend
var legend = svg.selectAll(".legend")
    .data(color.domain())
    .enter().append("g")
    .attr("class", "legend")
    .attr("transform", function(d, i) { return "translate(0," + i * 20 + ")"; });

legend.append("rect")
    .attr("x", width - 18)
    .attr("width", 18)
    .attr("height", 18)
    .style("fill", color);

legend.append("text")
    .attr("x", width - 24)
    .attr("y", 9)
    .attr("dy", ".35em")
    .style("text-anchor", "end")
    .text(function(d) { return d });



});

</script>

app/views/admin/get_sdn_config.html.erb
<h1>SDN switches configuration</h1>

<h4>Results:</h4>
<p></p>
<p>before:</p>
   <%= @starting_status.each do | item | %> 
      <%= item %><br>
   <% end %>
<p></p>
<hr>
<p>routes to the host network side of each switch:</p>
   <%= @step_one_status.each do | item | %> 
      <%= item %><br>
   <% end %>
<p></p>
<hr>
<p>routes for the networks interconnecting the switches:</p>
   <%= @step_two_status.each do | item | %> 
      <%= item %><br>
   <% end %>
<p></p>
<hr>
<p>default routes for the switches to talk to each other:</p>
  <%= @ending_status.each do | item | %> 
     <%= item %><br>
  <% end %>

<br>
<p> <%= link_to 'Back', controller: :admin %></p>

<p class="notice" id='notice' style='display:none; padding:10px'><%= notice %></p>

app/views/admin/index.html.erb
<h1>Switchboard Admin</h1>
<hr>
<h3>Links, IP addresses, and subnet management</h3>
<list>
	<li><%= link_to "Currently valid links", action: :links%></li>
	<li><%= link_to "Subnet, IP, and VLAN managers", admin_subnets_path%></li>
	<li><%= link_to "Group membership", controller: :owner_group%></li>
</list>
<hr>
<h3>SDN management</h3>
<list>
	<li><%= link_to "Visualize dynamic network configs",  home_visualize_sdn_path, :target => '_blank'%></li>
	<li><%= link_to "Fetch current SDN configuration from controller",  admin_get_sdn_config_path%></li>
	<li><%= link_to "Restore SDN state (playback saved default + dynamic configs)",  admin_playback_to_sdn_path%></li>
	<li><%= link_to "SDN status for monitoring",  monitor_glue_status_path%></li>
</list>
<h3>Default SDN controller and switch setup</h3>
<list>
	<li><%= link_to "Visualize default controller/switch configs",  admin_visualize_switch_setup_path, :target => '_blank'%></li>
	<li><%= link_to "Manage switch collection",  switches_path, :target => '_blank'%></li>
	<li><%= link_to "Default switch configs",  switch_initial_configs_path, :target => '_blank'%></li>
	<li><%= link_to "Initialize SDN controller with default configs",  admin_initialize_sdn_controller_path%></li>
</list>

app/views/admin/initialize_sdn.html.erb
<h1>SDN switches reset to initial configuration</h1>

<h4>Results:</h4>
<p></p>
<p>before:</p>
   <%= @starting_status.each do | item | %> 
      <%= item %><br>
   <% end %>
<p></p>
<hr>
<p>routes to the host network side of each switch:</p>
   <%= @step_one_status.each do | item | %> 
      <%= item %><br>
   <% end %>
<p></p>
<hr>
<p>routes for the networks interconnecting the switches:</p>
   <%= @step_two_status.each do | item | %> 
      <%= item %><br>
   <% end %>
<p></p>
<hr>
<p>default routes for the switches to talk to each other:</p>
  <%= @ending_status.each do | item | %> 
     <%= item %><br>
  <% end %>

<br>
<p> <%= link_to 'Back', controller: :admin %></p>

<p class="notice" id='notice' style='display:none; padding:10px'><%= notice %></p>

app/views/admin/subnets.html.erb
<h1>Subnet, IP, and VLAN Management</h1>
<%= link_to 'Back', controller: :admin %>

<p class="notice" id='notice' style='display:none; padding:10px'><%= notice %></p>

<h2>Subnets</h2>

<table border='0' class='tablesorter' cellspacing='1' cellpadding='0' width='100%' >
  <thead>
  <tr>
      <th >CIDR</th>
      <th >Owning Group</th>
      <th >Action</th>
    </tr>
  </thead>

  <tbody id='admin_list_tbody_id'>
    <% @subnets.each do |oo| %>
      <tr style="background-color:<%= cycle("#E6F2FF","white") %>">
				<td><%= oo.ownable.cidr %> </td>
				<td><div id='og_<%=oo.id%>'><div id='name_<%=oo.id%>' style='display:inline'><%= oo.owner_group.name %></div>
									<button class='chg_ip_owner' data-id = '<%=oo.id%>'>Change</button>
        <td><%= link_to 'Retire', admin_not_supported_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id='add_subnet' >
<%= form_tag('/admin/add_subnet') do%>
	
		<input id="cidr" name='cidr' type="text" placeholder="New Subnet CIDR" >
		<%= collection_select('new_group', '', OwnerGroup.all, :id, :name, {prompt: "Select owner group"}) %>
		<button id='add_subnet_btn'>&nbsp;</button>

<% end %>
</div>
<hr>
<h2>IPs</h2>

<table border='0' class='tablesorter' cellspacing='1' cellpadding='0' width='100%' >
  <thead>
  <tr>
      <th >IP address</th>
      <th >Owning Group</th>
      <th >Action</th>
    </tr>
  </thead>

  <tbody id='admin_list_tbody_id'>
    <% @owner_objs.each do |oo| %>
      <tr style="background-color:<%= cycle("#E6F2FF","white") %>">
				<td><%= oo.ownable.addr %> </td>
				<td><div id='og_<%=oo.id%>'><div id='name_<%=oo.id%>' style='display:inline'><%= oo.owner_group.name %></div>
					<button class='chg_ip_owner' data-id = '<%=oo.id%>'>Change</button>
        <td><%= link_to 'Retire', admin_not_supported_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id='add_ip' >
<%= form_tag('/admin/add_subnet') do%>
	
		<input id="ip" name='ip' type="text" placeholder="New IP" >
		<%= collection_select('new_group', '', OwnerGroup.all, :id, :name, {prompt: "Select owner group"}) %>
		<button id='add_ip_btn'>&nbsp;</button>

<% end %>
</div>
</div>
<hr>
<h2>VLANs</h2>

<table border='0' class='tablesorter' cellspacing='1' cellpadding='0' width='100%' >
  <thead>
  <tr>
     <th >VLAN</th>
     <th >Description</th>
     <th >Owning Group</th>
     <th >Action</th>
  </tr>
  </thead>

  <tbody id='admin_list_tbody_id'>
    <% @vlan_objs.each do |oo| %>
      <tr style="background-color:<%= cycle("#E6F2FF","white") %>">
		<td><%= oo.ownable.vlan_name %> </td>
		<td><%= oo.ownable.description %> </td>
		<td><div id='og_<%=oo.id%>'><div id='name_<%=oo.id%>' style='display:inline'><%= oo.owner_group.name %></div>
			<button class='chg_ip_owner' data-id = '<%=oo.id%>'>Change</button>
        <td><%= link_to 'Retire', admin_not_supported_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id='add_vlan' >
<%= form_tag('/admin/add_vlan') do%>
		<input id="vlan_name" name='vlan_name' type="text" placeholder="New VLAN" >
		<input id="description" name='description' type="text" placeholder="description" >	
		<%= collection_select('new_group', '', OwnerGroup.all, :id, :name, {prompt: "Select owner group"}) %>
		<button id='add_vlan_btn'>&nbsp;</button>

<% end %>
</div>

app/views/admin/switch_setup.html.erb
<h3>SDN switch setup configuration</h3>
<%=@switch_setup%>

app/views/admin/visualize_switch_setup.html.erb
<h3>SDN switch setup</h3>
<style>
iframe {
  width: 960px;
  height: 500px;
  border: 1px solid #DEDEDE;
}
aside {
  font-size: small;
  left: 780px;
  position: absolute;
  text-align: right;
  width: 180px;
}
</style>

<iframe src="/admin/d3_switch_setup" marginwidth="0" marginheight="0" scrolling="no"></iframe>

<br>
<p> <%= link_to 'Back', controller: :admin %></p>