config/routes.rb
Rails.application.routes.draw do

  resources :switch_initial_configs
  resources :switches


  get 'monitor_glue/status'

  get 'sdn_callback/restore_state'

  match 'net_config_transactions/sort' => 'net_config_transactions#sort', :via=>[:get, :post]
  resources :net_config_transactions, :only => [:index]
  
  get 'owner_group/index'
  get 'group/index'

  get 'admin/index'
  get 'admin'=>'admin#index'
  get 'admin/subnets'
  get 'admin/initialize_sdn_controller'
  get 'admin/playback_to_sdn'
  get 'admin/get_sdn_config'
  get 'admin/ajax_get_groups'
  post 'admin/ajax_set_group'
  get 'admin/ajax_get_members'
  post 'admin/add_subnet'
  get 'admin/links'
  delete 'admin/not_supported'
  
  get 'admin/visualize_switch_setup'
  get 'admin/d3_switch_setup'
  get 'admin/switch_setup'
  
  
  get 'home/logout'=>'home#logout'
  get "no_access" => 'home#no_access'
  get 'home/visualize_sdn'
  get 'home/d3_sdn'
  get 'home/sdn_status'
  
  root 'link_requests#index_get'
  match 'link_requests' => 'link_requests#index_get', :via=>[:get]
  
  post "link_requests/approve"
  post "link_requests/deny"  
  match 'link_requests/sort' => 'link_requests#sort', :via=>[:get, :post]
  resources :link_requests

  get "owner_group/ajax_users"
  post "owner_group/rm_user"
  post 'owner_group/add_user'
  match 'owner_group/sort' => 'owner_group#sort', :via=>[:get, :post]
  resources :owner_group
  

  get "activities/sort"
  resources :activities
  
  resources :links
  
end

app/models/switch_initial_config.rb
class SwitchInitialConfig < ActiveRecord::Base
   has_one :switch
   has_one :switch_connection_type

   def network_type
     SwitchConnectionType.find(self.switch_connection_type_id).name
   end

   def switch_name
     Switch.find(self.switch_id).name
   end
  
   def switch_description
     Switch.find(self.switch_id).description
   end
  
end

app/controllers/switch_initial_configs_controller.rb
class SwitchInitialConfigsController < ApplicationController
  
  before_filter :onlyAdmin
  before_action :set_switch_initial_config, only: [:show, :edit, :update, :destroy]
  before_action :cleanup_spaces, only: [:show, :edit, :update]
  
  # GET /switch_initial_configs
  # GET /switch_initial_configs.json
  def index
    @switch_initial_configs = SwitchInitialConfig.all
  end

  # GET /switch_initial_configs/1
  # GET /switch_initial_configs/1.json
  def show
  end

  # GET /switch_initial_configs/new
  def new
    @switch_initial_config = SwitchInitialConfig.new
  end

  # GET /switch_initial_configs/1/edit
  def edit
    
  end

  # POST /switch_initial_configs
  # POST /switch_initial_configs.json
  def create
    if user_entered_valid_ip( switch_initial_configs_url )
      @switch_initial_config = SwitchInitialConfig.new(switch_initial_config_params)
      respond_to do |format|
        if @switch_initial_config.save
          format.html { redirect_to @switch_initial_config, notice: 'Switch initial config was successfully created.' }
          format.json { render :show, status: :created, location: @switch_initial_config }
        else
          format.html { render :new }
          format.json { render json: @switch_initial_config.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /switch_initial_configs/1
  # PATCH/PUT /switch_initial_configs/1.json
  def update
    if user_entered_valid_ip( @switch_initial_config )
      @switch_initial_config.update(switch_initial_config_params)
      respond_to do |format|
        if @switch_initial_config.update(switch_initial_config_params)
          format.html { redirect_to @switch_initial_config, notice: 'Switch initial config was successfully updated.' }
          format.json { render :show, status: :ok, location: @switch_initial_config }
        else
          format.html { render :edit }
          format.json { render json: @switch_initial_config.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /switch_initial_configs/1
  # DELETE /switch_initial_configs/1.json
  def destroy
    @switch_initial_config.destroy
    respond_to do |format|
      format.html { redirect_to switch_initial_configs_url }
      format.json { head :no_content }
    end
  end

  private
    def user_entered_valid_ip( return_to_location )
      begin
        testing = IPAddress switch_initial_config_params[:ip]
      rescue => error_message
        respond_to do |format|
          format.html { redirect_to return_to_location, notice: "Cannot complete operation: #{error_message}"}
          format.json { render json: @switch_initial_config.errors, status: :unprocessable_entity }
        end
        return false
      else
        return true
      end     
    end
    
    
    def cleanup_spaces
      if !@switch_initial_config.vlan.nil?
        # strip any spaces from the vlan name
        @switch_initial_config.vlan = @switch_initial_config.vlan.gsub(' ', '')
        if @switch_initial_config.vlan.blank?
          @switch_initial_config.vlan = nil
        end
      end      
      if !@switch_initial_config.ip.nil?
        # strip any spaces from the ip address
        @switch_initial_config.ip = @switch_initial_config.ip.gsub(' ', '')
        if @switch_initial_config.ip.blank?
          @switch_initial_config.ip = '1.1.1.1/32' #bogus address as a placeholder
        end
      end      
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_switch_initial_config
      @switch_initial_config = SwitchInitialConfig.find(params[:id])
      cleanup_spaces
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def switch_initial_config_params
      params.require(:switch_initial_config).permit(:ip, :vlan, :switch_connection_type_id, :switch_id)
    end
end

app/helpers/switch_initial_configs_helper.rb
module SwitchInitialConfigsHelper
end

app/views/switch_initial_configs/_form.html.erb
<%= form_for(@switch_initial_config) do |f| %>
  <% if @switch_initial_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@switch_initial_config.errors.count, "error") %> prohibited this switch_initial_config from being saved:</h2>

      <ul>
      <% @switch_initial_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :switch_id %>
    <%= collection_select(:switch_initial_config, :switch_id, Switch.all, :id, :description) %>
  </div>
  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :vlan %>
    <%= f.text_field :vlan %>
  </div>
  <div class="field">
    <%= f.label :switch_connection_type_id %>
    <%= collection_select(:switch_initial_config, :switch_connection_type_id, SwitchConnectionType.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit :class=>'standard_button' %>
  </div>
<% end %>

app/views/switch_initial_configs/edit.html.erb
<h1>Editing Switch default configuration</h1>

<%= render 'form' %>

<%= link_to 'Show', @switch_initial_config %> |
<%= link_to 'Back', switch_initial_configs_path %>

app/views/switch_initial_configs/index.html.erb
<h1>Switch configurations</h1>

<table>
  <thead>
    <tr>
      <th>ip</th>
      <th>vlan</th>
      <th>network type</th>
      <th>switch</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @switch_initial_configs.each do |switch_initial_config| %>
      <tr style="background-color:<%= cycle("#E6F2FF","white") %>">
        <td style='padding:5px 10px 5px 5px'><%= switch_initial_config.ip %></td>
        <td style='padding:5px 10px 5px 5px'><%= switch_initial_config.vlan %></td>
        <td style='padding:5px 10px 5px 5px'><%= switch_initial_config.network_type %></td>
        <td style='padding:5px 10px 5px 5px'><%= switch_initial_config.switch_description %></td>
        <td style='padding:5px 10px 5px 5px'><%= switch_initial_config.switch_name %></td>
        <td style='padding:5px 10px 5px 5px'><%= link_to 'Show', switch_initial_config %></td>
        <td style='padding:5px 10px 5px 5px'><%= link_to 'Edit', edit_switch_initial_config_path(switch_initial_config) %></td>
        <td style='padding:5px 10px 5px 5px'><%= link_to 'Destroy', switch_initial_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Configuration', new_switch_initial_config_path %> | <%= link_to 'Edit Switches', switches_path %> |
<%= link_to 'Back', admin_path %> 

app/views/switch_initial_configs/new.html.erb
<h1>Switch configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', switch_initial_configs_path %>

app/views/switch_initial_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>switch description:</strong>
  <%= @switch_initial_config.switch_description %>
<br>
  <strong>switch id:</strong>
  <%= @switch_initial_config.switch_name %>
<br>
  <strong>ip:</strong>
  <%= @switch_initial_config.ip %>
<% if !@switch_initial_config.vlan.nil? %>
  <br>
    <strong>vlan:</strong>
    <%= @switch_initial_config.vlan %>
<% end %>
<br>
  <strong>network type:</strong>
  <%= @switch_initial_config.network_type %>

</p>

<%= link_to 'Edit', edit_switch_initial_config_path(@switch_initial_config) %> |
<%= link_to 'Switches', switches_path %> | <%= link_to 'Back', switch_initial_configs_path %>