config/routes.rb
Rails.application.routes.draw do

  resources :switch_initial_configs
  resources :switches


  get 'monitor_glue/status'

  get 'sdn_callback/restore_state'

  match 'net_config_transactions/sort' => 'net_config_transactions#sort', :via=>[:get, :post]
  resources :net_config_transactions, :only => [:index]
  
  get 'owner_group/index'
  get 'group/index'

  get 'admin/index'
  get 'admin'=>'admin#index'
  get 'admin/subnets'
  get 'admin/initialize_sdn_controller'
  get 'admin/playback_to_sdn'
  get 'admin/get_sdn_config'
  get 'admin/ajax_get_groups'
  post 'admin/ajax_set_group'
  get 'admin/ajax_get_members'
  post 'admin/add_subnet'
  get 'admin/links'
  delete 'admin/not_supported'
  
  get 'admin/visualize_switch_setup'
  get 'admin/d3_switch_setup'
  get 'admin/switch_setup'
  
  
  get 'home/logout'=>'home#logout'
  get "no_access" => 'home#no_access'
  get 'home/visualize_sdn'
  get 'home/d3_sdn'
  get 'home/sdn_status'
  
  root 'link_requests#index_get'
  match 'link_requests' => 'link_requests#index_get', :via=>[:get]
  
  post "link_requests/approve"
  post "link_requests/deny"  
  match 'link_requests/sort' => 'link_requests#sort', :via=>[:get, :post]
  resources :link_requests

  get "owner_group/ajax_users"
  post "owner_group/rm_user"
  post 'owner_group/add_user'
  match 'owner_group/sort' => 'owner_group#sort', :via=>[:get, :post]
  resources :owner_group
  

  get "activities/sort"
  resources :activities
  
  resources :links
  
end

app/models/link_request.rb
class LinkRequest < ActiveRecord::Base
  belongs_to :user
  has_many :approvals, autosave: true
  accepts_nested_attributes_for :approvals
  enum traffic:[ :ip_only, :layer_2]
  has_many :activities, :dependent => :delete_all
  
  after_create :create_activity
  
  #####################################################################
  # Validations
  #####################################################################

  validates :comment, presence: true
  validates :duration, presence: true
  validates :duration, numericality:{ only_integer: true }
  
  validate :uniqueness_of_ips
  validate :path_uniqueness
  
  # Override the icky representation of the nested model
  def self.human_attribute_name(attribute, options = {})  
    return "Requested Host" if (attribute.to_s == "approvals.ip.fqdn")
    attribute
  end
  
  # return a symbol for the current status
  def status
    s = :approved
    approvals.each do |a|
      case a.status
      when :pending, :error, :denied, :revoked, :deleted
        s = a.status
        break
      end
    end
    return s
  end
 
  # return a human readable version of the status
  def status_description()
    s = ''
    approvals.each do |a|
      s<< "#{a.ip.short_fqdn}: #{a.display_status}<br/>"
    end
    s.html_safe
  end
  
  def display
    approvals.each.collect{|a|a.ip.short_fqdn}.join(" to ")
  end
  
  # Send an email to concerned parties if necessary
  def send_approval_request
    # Build a list of all the approvers
    list = []
    approvals.each do |a|
      list += a.ip.owner_group.users.collect{|u| u.email }.uniq.compact unless [:tacit, :approved].include? a.status
    end
    puts "list is #{list}"
    SwitchboardMailer.approval_request_email(list.uniq, self).deliver unless list.blank?
  end
  
  # The originator approves this by default.
  def initial_approvals(user)
    set_final(:tacit, user)
    check_if_done
  end
  
  def approve_by(user)
    set_final(:approved, user)
    check_if_done
  end
  
  def deny_by(user)
    set_final(:denied, user)
  end

  def delete_by(user)
    set_final(:deleted, user)
    # configure the SDN link via the RYU router commands
    r = RyuController.new
    r.remove_static_routes(approvals[0].ip.addr, approvals[1].ip.addr, approvals[0].ip.vlan.vlan_name, approvals[1].ip.vlan.vlan_name )
  end
  
  def revoke_by(user)
    set_final(:revoked, user)
    # configure the SDN link via the RYU router commands
    r = RyuController.new
    r.remove_static_routes(approvals[0].ip.addr, approvals[1].ip.addr, approvals[0].ip.vlan.vlan_name, approvals[1].ip.vlan.vlan_name )
  end
  
  def can_be_approved_by(user)
    cba = false
    approvals.each do |a|
      cba ||= (a.status == :pending and  a.owner_group.users.include? user)
    end
    cba
  end
  
  def owned_by(user)
    cba = false
    approvals.each do |a|
      cba ||= a.owner_group.users.include? user
    end
    cba
    
  end
  
  def create_activity
    Activity.create(user: user, verb: 'create', link_request: self, occurred: Time.now)
  end
  
  # CLASS METHODS
  def self.getApprovalsForUser(user=nil)
    if user.blank?
      LinkRequest.joins(:approvals).where("approvals.status = 'PENDING'").uniq
    else
      LinkRequest.joins(approvals: [owner_group: :users]).where("owner_groups_users.user_id = ? " +
        " AND approvals.status = 'PENDING'", user.id).uniq
    end
  end
  
  # Return all requests that are fully approved and still valid 
  def self.valid
    self.includes(approvals: :ip).collect{|lr| lr if (lr.status == :approved) && (lr.end >= Time.now)}.compact
  end
  
  
  def path_uniqueness
    LinkRequest.valid.each do |lr|
      apps = lr.approvals.collect{|a|a.ip}
      match = true
      approvals.each do |myapp|
        match &&= apps.include? myapp.ip
      end
      if match
        errors.add(:"approvals.ip.fqdn", "not unique: this link already exists") if errors[:"approvals.ip.fqdn"].blank? 
        break
      end
    end
  end

  private
  # Check ips to see if we have duplicates.  The IP object may not be saved yet so we'd better calculate it.
  def uniqueness_of_ips
    hash = {}
    approvals.each do |a|
      addr = a.ip.addr.blank? ? a.ip.calc_addr : a.ip.addr
      if hash[addr]
       # This line is needed to inform the parent to error out, otherwise the save would still happen
        errors.add(:"approvals.ip.fqdn", "nonunique host error") if errors[:"approvals.ip.fqdn"].blank? 
      end
      hash[addr] = true
    end
  end
  
  # If completely approved, set start and end dates
  def check_if_done
    return unless status == :approved
    self.start = Time.now
    self.end = Time.now + (duration.to_i).month
    self.save validate: false
    
    # set up the SDN link via the RYU router commands
    r = RyuController.new
    
    r.connect_via_static_routes(approvals[0].ip.addr, approvals[1].ip.addr, approvals[0].ip.vlan.vlan_name, approvals[1].ip.vlan.vlan_name )
  end
  
  def set_final(state, user)
    approvals.each do |a|
      a.set_final_status(state, user)
    end
  end
  
end

app/controllers/link_requests_controller.rb
class LinkRequestsController < ApplicationController
  before_action :set_link_request, only: [:show, :edit, :update, :destroy, :approve, :deny]

  def index_get
    return do_page(cookies[:justMine], cookies[:show_admin],cookies[:show_admin_approval])
  end

  def index
    return do_page
  end

  def sort
    return do_page
  end

  # GET /link_requests/1
  # GET /link_requests/1.json
  def show
    
  end

  # GET /link_requests/new
  def new
    @link_request = LinkRequest.new
    2.times { 
      ap = @link_request.approvals.build 
      ap.ip = Ip.new
      ap.ip.vlan = Vlan.first  #default to the first VLAN, which is the default (null) VLAN
    }
  end

  # GET /link_requests/1/edit
  def edit
    respond_to do |format|
      format.html { redirect_to @link_request, notice: 'Updates to requests are not allowed' }
      format.json { render json: ["updates not allowed"], status: :unprocessable_entity }
    end
    
  end

  # POST /link_requests
  # POST /link_requests.json
  def create
    logger.info "link_requests_controller.create: you have #{link_request_params}"
    
    @link_request = LinkRequest.new(link_request_params)
    @link_request.user = @user
    respond_to do |format|
      if @link_request.save
        @link_request.initial_approvals(@user)  # Approve what you can as the originator
        @link_request.send_approval_request
        format.html { redirect_to @link_request, notice: 'Link request was successfully created.' }
        format.json { render :show, status: :created, location: @link_request }
      else
        format.html { render :new }
        format.json { render json: @link_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /link_requests/1
  # PATCH/PUT /link_requests/1.json
  def update
    respond_to do |format|
      format.html { redirect_to @link_request, notice: 'Updates to requests are not allowed' }
      format.json { render json: ["updates not allowed"], status: :unprocessable_entity }
    end
  end

  # DELETE /link_requests/1
  # DELETE /link_requests/1.json
  def destroy
    unless @link_request.owned_by(@user)
      logger.error "#{@user.netid} tried to delete request #{@link_request.id}"
      return redirect_to link_requests_path, notice: "You do not have enough access to delete that request"
    end
    # if @link_request.status == :approved
      @link_request.delete_by(@user)
    # else
    #   @link_request.destroy
      Activity.create(user: @user, verb: 'destroy', link_request: @link_request, occurred: Time.now)
    # end
  
    respond_to do |format|
      format.html { redirect_to link_requests_url }
      format.json { head :no_content }
    end
  end
  
  def approve
    respond_to do |format|
      if @link_request.approve_by(@user)
        format.html { redirect_to @link_request, notice: 'Link request was succesfully approved' }
        format.json { render :show, status: :ok, location: @link_request }
      else
        format.html { redirect_to @link_request, notice: 'Failed to approve request' }
        format.json { render json: @link_request.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def deny
    respond_to do |format|
      if @link_request.deny_by(@user)
        format.html { redirect_to @link_request, notice: 'Link request was succesfully denied' }
        format.json { render :show, status: :ok, location: @link_request }
      else
        format.html { redirect_to @link_request, notice: 'Failed to deny request' }
        format.json { render json: @link_request.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def items
    {'Host A' => 'not_sortable', 'Host B' => 'not_sortable',  
      'Requester' => 'user_id', 'Date Requested' => 'created_at', 'Status' => "status"}
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_request
      @link_request = LinkRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_request_params
      params.require(:link_request).permit(:id, :show_admin, :traffic, :comment, :duration, 
                                            approvals_attributes: [ :status, ip_attributes:[:fqdn, :vlan_id] ])
    end
    
    def do_page(init_justmine = true, init_showadmin = false, init_show_admin_approval=false)
      @curOrder =params[:curOrder].presence || "created_at"
      @curDir = params[:curDir].presence || 'false'
      @order = params[:order].presence || @curOrder

      f= params[:just_mine].presence || init_justmine
      
      @justMine = f.eql? 'true'
      if @user.isAdmin?
        f = params[:show_admin].presence || init_showadmin
        @show_admin = f.eql? 'true'
      else
        @show_admin = false
      end

      if @curOrder.eql?(@order)
        @curDir = @curDir.eql?('false') ? true : false
      else
        @curDir = false
        @curOrder = @order
      end
      ob = "#{@curOrder} "+ (@curDir ? 'DESC':'ASC')

      f= params[:show_admin_approval].presence || init_show_admin_approval
      @adminApproval = f.eql? 'true'
      if @adminApproval
        @approvals = LinkRequest.getApprovalsForUser()
      else
        @approvals = LinkRequest.getApprovalsForUser(@user)
      end
      

      if @justMine
        @reqs = @show_admin ?  LinkRequest.all.order(ob) :  @user.link_requests.order(ob)
        
      else
        @reqs = LinkRequest.joins(approvals: [owner_group: :users]).where(
        "(link_requests.user_id = #{@user.id}) OR (" +
        "owner_groups_users.user_id = #{@user.id} " +
        ")").order(ob).uniq
      end
      @items = items()
      logger.info "items is #{@items}"
      cookies[:justMine] = @justMine
      cookies[:show_admin]=@show_admin
      cookies[:show_admin_approval]=@adminApproval
      @reqs = @reqs.paginate(:page => params[:page])
      render :action=>:index
      
    end
    
end

app/helpers/link_requests_helper.rb
module LinkRequestsHelper
  def buildOwnerGroup(app)
    list = app.ip.owner_group.users.each.collect{|u| u.displayName}.join('</li><li>')
    s = "<a href='#' title='Owning Group: #{app.ip.owner_group.name}<br/><ul><li>#{list}</li></ul>'>
    #{app.ip.short_fqdn} VLAN: #{app.ip.vlan.display}</a> #{app.display_status}<br/>"
    
    s = "<a href='#' title='Owning Group: #{app.ip.owner_group.name}<br/><ul><li>#{list}</li></ul>'>#{app.ip.short_fqdn} "
    if (!app.ip.vlan.blank?)
      if (!app.ip.vlan.vlan_name.blank?)
        s += "VLAN: #{app.ip.vlan.display}"
      end
    end
    s += "</a> #{app.display_status}<br/>"
    
    ret = %Q{

    }
    return s.html_safe
  end
end

app/views/link_requests/_approval.html.erb
<td><% unless approval.blank?%>
    <%= approval.ip.fqdn %><br/>
    <% if !approval.ip.vlan.blank?%>
      <% if !approval.ip.vlan.vlan_name.blank?%> 
        VLAN: <%= approval.ip.vlan.display %><br/>
      <% end %>
    <% end %>
    <%= approval.status_display %>
  <% else %>
		Missing?
  <% end %>
</td>

app/views/link_requests/_approval_fields.html.erb
<div>
<%= f.fields_for :ip do |builder| %>
    <%= builder.label "hostname" %>
    <%= builder.text_field :fqdn, size: 60 %><br>
    <%= builder.label 'VLAN: ' %>
    <%= builder.select(:vlan_id, Vlan.all.collect {|v| [ v.display, v.id ] }, {select: 1}) %>
<% end %>
    
</div>

app/views/link_requests/_form.html.erb
<%= form_for(@link_request) do |f| %>
  <% if @link_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link_request.errors.count, "error") %> prohibited this Link Request from being saved:</h2>

      <ul>
      <% @link_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
<fieldset>
	<legend>Link Requirements</legend>
	<div id='securenet'>
	  <%= f.label 'Allowed Traffic' %>
	  <%= f.select :traffic, options_for_select(LinkRequest.traffics.keys), prompt: 'Please Select' %>
	</div>
  
		<%= f.fields_for :approvals do |builder| %>
		  <%= render 'approval_fields', :f => builder %>
		<% end %>
		
		<div >
    <%= f.label "Project Description" %>
    <%= f.text_area :comment, :rows=>9, :cols=>70 %>
  </div>
  <div >
		<label for="Link Duration" >Link Duration <%= image_tag(asset_path("information2.png"), width:"16" )%></label>
    <%= f.text_field :duration, :size=>4%> Months (est)
  </div>
</fieldset>
	
  <div class="actions">
    <%= f.submit :class=>'standard_button' %>
  </div>
<% end %>

app/views/link_requests/_link_request.html.erb
<%
		bcolor = 'draft_tr'
		bcolor = 'pending_tr' if  :pending == req.status
		bcolor = 'bogus_tr' if req.status == :denied 
		bcolor = 'complete_tr' if req.status == :approved
		bcolor = 'error_tr' if req.status == :error or req.status == :revoked

%>
  <tr <%="class=#{bcolor}" unless bcolor.blank? %> >
		
		<%= render( :partial => "approval", collection: req.approvals, as: :approval) %>
		<td><%= req.user.short_display %></td>
		
    <td><%= req.created_at.strftime("%Y-%m-%d %H:%M") unless req.created_at.blank?%></td>
    <td><div id='status_div_<%=req.id%>' class="status_div" data-vmreqid="<%=req.id%>"><%= req.status%>
			 </div>
		</td>
    <td>
			<% if for_approve %>
      	<%=link_to("Approve",req)%>
			<% else %>
     	 <%=link_to("View",req)%>
	      
				<% if req.status == :approved%>
	      |	<%= link_to 'Revoke', req, method: :delete, data: { confirm: 'Are you sure? This will make this link invalid and it will have to be re-requested to activate again.' } %>
				<% elsif req.status != :revoked and req.owned_by(@user)%>
	      |	<%= link_to 'Delete', req, method: :delete, data: { confirm: 'Are you sure?  This will completely remove the Link request even though parts of it may already be approved.' } %>
				<% end %>
			<% end %>
    </td>
  </tr>

app/views/link_requests/edit.html.erb
<h1>Editing link_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @link_request %> |
<%= link_to 'Back', link_requests_path %>

app/views/link_requests/index.html.erb
<h3>SDN network </h3>
<%= link_to "View current network configuration",  home_visualize_sdn_path, :target => '_blank'%></li>

<% unless @approvals.blank? or !@user.isAdmin? %>
    <hr>
	<h3>Pending Approvals</h3>
	<% if @user.isAdmin? %>
		<div>
			<%= form_tag('/link_requests/sort') do %>
				<%= check_box_tag 'show_admin_approval', !@adminApproval, @adminApproval, :onchange => "this.form.submit();"%>
				Show all pending approvals - Admin Only
				<%= hidden_field_tag 'show_admin', @show_admin%>
				<%= hidden_field_tag 'just_mine', @justMine%>
			<% end %>
		</div>
	<% end %>
	
	<table border='0' class='tablesorter' cellspacing='1' cellpadding='0' width='100%' >
	  <thead>
	  <tr>
			<% @items.each_pair{|key,value|%>
				<th class='no_sort_header'> <%= key %> </th>
			<% } %>
			<th class='action'>Action</th>
	  </tr>
	  </thead>
	  <tbody id='admin_list_tbody_id'>
		<%= render( :partial => "link_request", collection: @approvals, as: :req, locals: {for_approve: true}) %>
	</table>
	<hr>
<% end %>

<hr>
<h3>Request SDN configuration change</h3>
<div style='float:left;'>
	<%= button_to "Request New Link", new_link_request_path, :class=>'standard_button', :method => :get %>
</div><div style='float:left;'>
	<%= form_tag('/link_requests/sort') do %>
		<%= check_box_tag 'just_mine', !@justMine, @justMine, :onchange => "this.form.submit();"%>
		Show Just My Requests		
		<%= hidden_field_tag 'show_admin_approval', @adminApproval%>
		<%= hidden_field_tag 'show_admin', @show_admin%>
	<% end %>

</div>

<% if @user.isAdmin? %>
	<div style='float:left'>
		<%= form_tag('/link_requests/sort') do %>
			<%= check_box_tag 'show_admin', !@show_admin, @show_admin, :onchange => "this.form.submit();"%>
			Show requests for all users - Admin Only
			<%= hidden_field_tag 'show_admin_approval', @adminApproval%>
			<%= hidden_field_tag 'just_mine', @justMine%>
		<% end %>
	</div>
<% end %>

<div style="clear:both;"></div>

<% if @reqs.blank? %>

	<p>You don't have any Link requests.</p>

<% else %>

<table border='0' class='tablesorter' cellspacing='1' cellpadding='0' width='100%' >
  <thead>
  <tr>
		<% @items.each_pair{|key,value|
			if value == 'not_sortable'
				%>
				<th class='no_sort_header'><%= key%></th>
				<%
			else
				klass = 'header '
				if value == @curOrder
					klass += @curDir ? 'headerSortDown' : 'headerSortUp'
				end
					%>
	<th class='<%=klass%> <%=value%>'><%= link_to "#{key} &nbsp;".html_safe,  {:action=>:sort, :order=>value, :curOrder=>@curOrder,:curDir=>@curDir,:searchClause=>@searchClause,:just_mine=>@justMine,:show_admin=>@show_admin} %></th>
					<%
			end
		} %>
		<th class='action'>Action</th>
  </tr>
  </thead>
  <tbody id='admin_list_tbody_id'>
	<%= render( :partial => "link_request", collection: @reqs, as: :req, locals: {for_approve: false}) %>
</table>

<div class="apple_pagination">
	<div class="page_info">
		<%= page_entries_info @reqs %>
	</div>
	<%= will_paginate @reqs,  :params=>{:just_mine=>@justMine,:show_admin=>@show_admin}, :container => false %>
</div>
<% end %>

app/views/link_requests/new.html.erb
<h1>New Link Request</h1>


<%= render 'form' %>

<%= link_to 'Back', link_requests_path %>

app/views/link_requests/show.html.erb
<p id="notice"><%= notice %></p>

<fieldset class='show_requests'>
	<legend>Link Requirements</legend>
  
	<% @link_request.approvals.each do |approval| %>
	<div>
		<label>Host:</label> <%= approval.ip.fqdn %>
		<% if !approval.ip.vlan.nil?  %>
		    <% if !approval.ip.vlan.vlan_name.blank?  %>
			<br><label>VLAN:</label> <%= approval.ip.vlan.display %>
			<% end %>
		<% end %>
	</div>
	<% end %>
		
		<div>
		<label>Type of Traffic</label>   <%= @link_request.traffic %>
	</div>
	<div>
		<label>Estimated Duration Requested</label>   <%= @link_request.duration %> Months
	</div>
	<div>
    <label>Comments</label>
    <%= simple_format(@link_request.comment) %>
  </div>
	<div>
		<div style='float:left'>
    <label>Current State</label></div>
    <div style='display:inline'>
			
			<% @link_request.approvals.each do |a| %>
				<%= buildOwnerGroup(a)%>
			<% end %>	
		</div>
	</div>
	
	<% if @link_request.status == :approved %>
	<div>
    <label>Start Date</label> <%= @link_request.start.strftime("%Y-%m-%d") %>
	</div>
	<div>
    <label>Expected End Date</label> <%= @link_request.end.strftime("%Y-%m-%d") %>
	</div>
	
	<% end %>

</fieldset>
	<div style='margin-top:20px;float:left;'>
	
<% if @link_request.can_be_approved_by(@user) %>

<%= button_to "Approve Link", {action: :approve, id: @link_request.id}, :class=>'standard_button' %>
	</div>
	<div style='margin-top:20px;float:left;'>
		<%= button_to "Deny Link Request", {action: :deny, id: @link_request.id}, :confirm => 'Are you sure you want to Deny this request? The request process will be terminated.', :class=>'standard_button' %>
	</div>
	<div style='margin-top:20px;float:left;'>

<% end %>
	<%= link_to "Back", link_requests_path%>
	</div>