config/routes.rb
Rails.application.routes.draw do

  resources :switch_initial_configs
  resources :switches


  get 'monitor_glue/status'

  get 'sdn_callback/restore_state'

  match 'net_config_transactions/sort' => 'net_config_transactions#sort', :via=>[:get, :post]
  resources :net_config_transactions, :only => [:index]
  
  get 'owner_group/index'
  get 'group/index'

  get 'admin/index'
  get 'admin'=>'admin#index'
  get 'admin/subnets'
  get 'admin/initialize_sdn_controller'
  get 'admin/playback_to_sdn'
  get 'admin/get_sdn_config'
  get 'admin/ajax_get_groups'
  post 'admin/ajax_set_group'
  get 'admin/ajax_get_members'
  post 'admin/add_subnet'
  get 'admin/links'
  delete 'admin/not_supported'
  
  get 'admin/visualize_switch_setup'
  get 'admin/d3_switch_setup'
  get 'admin/switch_setup'
  
  
  get 'home/logout'=>'home#logout'
  get "no_access" => 'home#no_access'
  get 'home/visualize_sdn'
  get 'home/d3_sdn'
  get 'home/sdn_status'
  
  root 'link_requests#index_get'
  match 'link_requests' => 'link_requests#index_get', :via=>[:get]
  
  post "link_requests/approve"
  post "link_requests/deny"  
  match 'link_requests/sort' => 'link_requests#sort', :via=>[:get, :post]
  resources :link_requests

  get "owner_group/ajax_users"
  post "owner_group/rm_user"
  post 'owner_group/add_user'
  match 'owner_group/sort' => 'owner_group#sort', :via=>[:get, :post]
  resources :owner_group
  

  get "activities/sort"
  resources :activities
  
  resources :links
  
end

app/models/activity.rb
require 'csv'
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :link_request
  belongs_to :ip
  
  def self.to_csv(acts)
    CSV.generate do |csv|
      csv << column_names
      acts.each do |act|
        row = []
        Activity.column_names.each do |col|
          row << case col
          when 'ip_id'
            act.ip.short_fqdn unless act.ip.blank?
  #        when 'vlan_id'
  #          act.ip.vlan.display unless act.ip.vlan.blank?
          when 'user_id'
            act.user.displayName
          when 'link_request_id'
            act.link_request.approvals.each.collect{|a|"#{a.ip.short_fqdn}"}.join("|")
          else
            act.send(col)
          end
        end
        csv << row
      end
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    return do_page if params[:view_type] == 'table'
    
    @activities = Activity.includes([:ip, :user, :link_request => [approvals: :ip]]).where("link_request_id IS NOT NULL" ).reverse_order
    @actHash = {}
    @activities.each do |a|
      dString = a.occurred.strftime("%b %d")
      @actHash[dString] = [] unless @actHash.has_key? dString
      
      if a.ip.blank?
        desc = a.link_request.display
      else
        desc = a.ip.short_fqdn 
        if !a.ip.vlan.blank?
          desc += " with VLAN: #{a.ip.vlan.display}"
        end
              
      end
      
      @actHash[dString] << {url: "<a href='/link_requests/#{a.link_request.id}'>#{desc} - #{a.verb} by #{a.user.displayName}</a>",
         acttime: a.occurred.strftime("%I:%M %p")}

    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actHash }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  def sort
    return do_page
  end
  
  private
  
    def do_page
      @items = {"Actor"=>'', 'Action'=>'verb',  "Ip" => "",  'Link Request'=>'', 'When' => 'occurred'}
      @curOrder =params[:curOrder].presence || "occurred"
      @curDir = params[:curDir].presence || 'false'
      @order = params[:order].presence || @curOrder
      @searchClause = params[:searchClause]
      
      if @curOrder.eql?(@order)
        @curDir = @curDir.eql?('false') ? true : false
      else
        @curDir = false
        @curOrder = @order
      end
      ob = "#{@curOrder} "+ (@curDir ? 'DESC':'ASC')
      
      unless @searchClause.blank?
        sc = <<-SQL 
SELECT * FROM (
SELECT a.* from activities a
INNER JOIN link_requests lr ON lr.id = a.link_request_id
INNER JOIN approvals ap ON lr.id = ap.link_request_id
JOIN ips ON ap.ip_id = ips.id
JOIN vlans ON vlans.id = ips.vlan_id
WHERE UPPER(ips.fqdn) like ?
UNION
SELECT a.* FROM activities a
INNER JOIN users u ON a.user_id = u.id
WHERE UPPER(u.netid) LIKE ?
OR UPPER(u.displayName) LIKE ?
OR UPPER(a.verb) LIKE ?
) allacts ORDER BY ?
SQL
        clike = "%#{@searchClause.upcase}%"
        @acts = Activity.paginate_by_sql([sc, clike,clike,clike,clike,ob],:page => params[:page])
      
      else
        @acts = Activity.includes([:ip, :user, :link_request => [approvals: :ip]]).order(ob).paginate(:page => params[:page])
        
      end
      respond_to do |format|
        format.html { render :index_table}
        format.csv { send_data Activity.to_csv(@acts) }
        format.json { render json: @acts }
      end
      
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params[:activity]
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/_menu_options.html.erb
<div id='act_menu'>
	<span>Activities 
		<input class="settings_btn" id='menu_button' type="button"  />
	</span>
	<div id='popupmenu'>
		<ul>
			
			<li <% if (params[:view_type].blank?  ) %>class="active"<% end %>><%=link_to 'Stream', activities_path %></li>
			<li <% if (params[:view_type] == 'table'  ) %>class="active"<% end %>><%=link_to 'Table', activities_path(view_type: 'table')%></li>
			<li><%=link_to 'CSV', activities_path(view_type: 'table', format: 'csv')%></li>
		</ul>
	</div>
</div>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<%= render 'menu_options'%>
<% 
even = true
@actHash.each_pair do |actDate, acts| 
	even = !even
%>

<div class='day'>
<a href="#" class="decorated" data-default-stack="true">
<span><span><%=actDate%></span></span>
</a>
</div>

<div class="project chiral <%=even ? 'left':'right'%>" style="display: block;">
</div>

<% acts.each do |act| %>

<article class="event chiral <%=even ? 'left':'right'%>" data-side="<%=even ? 'left':'right'%>">
  <div class="time">
    <span class="time_only"><time><%=act[:acttime]%></time></span>
  </div>
  <div class="action">
    <span class="creator"> <%= act[:url].html_safe%></span>
  </div>
</article>
<% end %>

<% end %>

app/views/activities/index_table.html.erb
<%= render 'menu_options'%>

<div id='search' style='float:right; margin-top:13px'>
<script type="text/javascript">
function doSearch() {
	var s = document.getElementById('searchClause');
	location = "/activities/sort?curDir=<%=@curDir%>&curOrder=<%=@curOrder%>&order=<%=@curOrder%>&page=1&searchClause="+s.value;
	return false;
}
</script>
		<%= submit_tag 'Search', :onClick=>'return doSearch();', :class=>'standard_button'%>
		<%= text_field_tag "searchClause", @searchClause, :size=>40, :onKeydown=>'if (event.keyCode==13) doSearch();' %>
</div>

<table class='act_table' border='2' cellspacing='5' cellpadding='5' width='100%'>
	
  <thead>
  <tr>
		<% @items.each_pair{|key,value|
			klass = 'header '
			if value.blank?
				%>
				<th class='no_sort'><%= key %></th>
				<%
			else	
				if value == @curOrder
					klass += @curDir ? 'headerSortDown' : 'headerSortUp'
				end
		%>
			<th class='<%=klass%> <%=value%>'><%= link_to "#{key} &nbsp;".html_safe,  {:action=>:sort, :order=>value, :curOrder=>@curOrder,:curDir=>@curDir,:searchClause=>@searchClause} %></th>
		<% end
	   } %>
  </tr>
  </thead>
	
	<tbody id='admin_list_tbody_id'>

		<% 	@acts.each do |act| %>
	<tr style="background-color:<%= cycle("#E6F2FF","white") %>">
    <td><%=act.user.displayName unless act.user.blank?%> </td>
    <td><%=act.verb%> </td>
		<td><%=act.ip.short_fqdn unless act.ip.blank?%></td>
    <td>
			<ul>
				<% act.link_request.approvals.each do |app| %>
				<li>
					<%= app.ip.short_fqdn %>
					<% if !app.ip.vlan.blank? %>
					    with VLAN: <%= app.ip.vlan.display %>
					<% end %>
				</li>
				<% end %> 
			</ul>
		</td>
		<td><%=act.occurred.strftime("%Y-%m-%d %H:%M")   %></td>
		
  </tr>
<% end %>
	</tbody>
</table>

<div class="apple_pagination">
	<div class="page_info">
		<%= page_entries_info @acts %>
	</div>
	<%= will_paginate @acts %>
</div>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>